---
abstract: 'Yeb Plugin for Text::Xslate'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Test::LoadAllModules: '0.021'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Yeb-Plugin-Xslate
requires:
  Moo: '0'
  Text::Xslate: '0'
  Yeb: '0.100'
resources:
  homepage: https://github.com/Getty/p5-yeb-plugin-xslate
  repository: https://github.com/Getty/p5-yeb-plugin-xslate.git
version: '0.001'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::GETTY/@Basic/GatherDir'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::GETTY/@Basic/PruneCruft'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::GETTY/@Basic/ManifestSkip'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::GETTY/@Basic/MetaYAML'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::GETTY/@Basic/License'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::GETTY/@Basic/Readme'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::GETTY/@Basic/ExtraTests'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::GETTY/@Basic/ExecDir'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::GETTY/@Basic/ShareDir'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::GETTY/@Basic/MakeMaker'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::GETTY/@Basic/Manifest'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::GETTY/@Basic/TestRelease'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::GETTY/@Basic/ConfirmRelease'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::GETTY/@Basic/UploadToCPAN'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::GETTY/Git::NextVersion'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::GETTY/PkgVersion'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::GETTY/MetaConfig'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::GETTY/MetaJSON'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::GETTY/PodSyntaxTests'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::GETTY/Repository'
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::GETTY/GithubMeta'
      version: '0.42'
    -
      class: Dist::Zilla::Plugin::TravisCI
      name: '@Author::GETTY/TravisCI'
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::GETTY/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::GETTY/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::GETTY/Git::CheckFor::CorrectBranch'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::GETTY/TestsOfAuthorGETTY'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::GETTY/ChangelogFromGit'
      version: '0.015'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@Author::GETTY'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@GETTY/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@GETTY/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@GETTY/Prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Synopsis'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Description'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Overview'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Stability'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@GETTY/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@GETTY/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Bugs
              name: '@GETTY/Bugs'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@GETTY/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@GETTY/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@GETTY/List'
              version: '4.006'
      name: '@Author::GETTY/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::GETTY/@Git/Check'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::GETTY/@Git/Commit'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::GETTY/@Git/Tag'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::GETTY/@Git/Push'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.013'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.013'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.013'
x_authority: cpan:GETTY
